### ISSUE TITLE
Does not work on ruby version >= 2.2 File.exists? is deprecated.

### ISSUE THREAD

**Issue by jward7** [biola/turnout#66]
Does not work on ruby version >= 2.2 File.exists? deprecated. File.exist? should work.

❯ rake maintenance:start
(in /Users/jward/programming/projects/finance/trade)
rake aborted!
NoMethodError: undefined method `exists?' for class File (NoMethodError)

      File.exists? path
          ^^^^^^^^
Did you mean?  exist?

Tasks: TOP => maintenance:start
(See full trace by running task with --trace)
